modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "aggressive_mobs"
version = "${version}"
displayName = "Aggressive Mobs"
authors = "Zamecki"
description = '''
Simply put, every mob is now aggressive.
'''
#logoFile = ""

[[dependencies.aggressive_mobs]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aggressive_mobs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aggressive_mobs]]
modId = "architectury"
type = "required"
versionRange = "[16.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "aggressive_mobs.mixins.json"
